function record = uls_record_from_floor_envelope(floorEnvelope)
%ULS_RECORD_FROM_FLOOR_ENVELOPE Flatten floor envelope into Step 10 ULS record.

validateFloorEnvelope(floorEnvelope);

record = struct( ...
    'floor_id', floorEnvelope.floor_id, ...
    'direction_case', floorEnvelope.direction_case, ...
    'environment_case', floorEnvelope.environment_case, ...
    'beta_wind', floorEnvelope.beta_wind, ...
    'beta_wave', floorEnvelope.beta_wave, ...
    'controls', floorEnvelope.controls, ...
    'leg_ratio', floorEnvelope.leg_ratio, ...
    'brace_ratio', floorEnvelope.brace_ratio);

if strcmp(floorEnvelope.controls, 'leg')
    record.member_type = 'leg';
    record.demand = floorEnvelope.demands.max_leg_compression;
    record.capacity = floorEnvelope.leg_capacity;
    record.member_id = floorEnvelope.demands.compression_leg_id;
else
    record.member_type = 'brace';
    record.demand = floorEnvelope.demands.max_brace_compression;
    record.capacity = floorEnvelope.brace_capacity;
    record.member_id = floorEnvelope.demands.brace_id;
end
end

function validateFloorEnvelope(floorEnvelope)
requiredFields = { ...
    'floor_id', 'direction_case', 'environment_case', 'beta_wind', 'beta_wave', ...
    'controls', 'leg_ratio', 'brace_ratio', 'demands', 'leg_capacity', 'brace_capacity'};
if ~isstruct(floorEnvelope)
    error('uls_record_from_floor_envelope:InvalidEnvelope', ...
        'floorEnvelope must be a struct.');
end
for i = 1:numel(requiredFields)
    if ~isfield(floorEnvelope, requiredFields{i})
        error('uls_record_from_floor_envelope:MissingField', ...
            'floorEnvelope must contain field ''%s''.', requiredFields{i});
    end
end
if ~isfield(floorEnvelope.demands, 'max_leg_compression') ...
        || ~isfield(floorEnvelope.demands, 'max_brace_compression') ...
        || ~isfield(floorEnvelope.demands, 'compression_leg_id') ...
        || ~isfield(floorEnvelope.demands, 'brace_id')
    error('uls_record_from_floor_envelope:MissingDemandField', ...
        'floorEnvelope.demands must contain compression and brace demand fields.');
end
end
