function manifest = directional_validation_manifest()
%DIRECTIONAL_VALIDATION_MANIFEST Step 11 minimum validation test mapping.
%
% Each entry maps a PLAN Step 11 requirement to an executable test script
% under Validations/model/.

manifest(1) = makeEntry( ...
    'direction_scenario_table', ...
    'Test_direction_scenarios.m', ...
    'Direction scenario table (D1-D4 / SINGLE / LEGACY)');
manifest(2) = makeEntry( ...
    'eq48_algebra', ...
    'Test_combine_plan_loads.m', ...
    'Eq. (48) load combination algebra');
manifest(3) = makeEntry( ...
    'four_leg_envelope', ...
    'Test_uls_member_demands.m', ...
    'Four-leg compression/tension envelope hand checks');
manifest(4) = makeEntry( ...
    'beta0_hydro_regression', ...
    'Test_wave_angle_kinematics.m', ...
    'beta_wave=0 hydrodynamics regression');
manifest(5) = makeEntry( ...
    'mode_dispatch', ...
    'Test_direction_mode_selection.m', ...
    'Mode dispatch for auto_envelope / single_direction / legacy_pesai');
manifest(6) = makeEntry( ...
    'summary_metadata', ...
    'Test_write_directional_summary.m', ...
    'Directional summary metadata formatting and validation');
end

function entry = makeEntry(requirementId, testScript, description)
entry = struct( ...
    'requirement_id', requirementId, ...
    'test_script', testScript, ...
    'description', description);
end
