%RUN_STEP5_PERFORMANCE_PROFILE Time directional Step 5 envelope path (smoke scale).
thisFileDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(thisFileDir);
logFile = fullfile(thisFileDir, 'test_directional_performance_log.txt');
addpath(fullfile(projectRoot, 'modules'));

global Member Hydro Wave Current Discrete debug dL_ele_target
debug = 0;
dL_ele_target = 3.0;
Hydro = struct('density', 1025, 'cd', 1.0, 'cm', 2.0);
Wave = struct('S', 50, 'T', 12.49, 'h', 10, 'k', wave_number(12.49, 50), 'beta_propagation', 0);
Current = struct('U_ss0', 0, 'U_ns0', 0, 'h_ref', 20, 'Vc', 0);
Member = struct();
Member.X0(1) = 0;
Member.Y0(1) = 0;
Member.Z0(1) = 0;
Member.X0(2) = 10;
Member.Y0(2) = 0;
Member.Z0(2) = 4;
Member.X0(3) = 12;
Member.Y0(3) = 0;
Member.Z0(3) = -4;
Member.X0(4) = -8;
Member.Y0(4) = 0;
Member.Z0(4) = -4;
Member.X0(5) = -10;
Member.Y0(5) = 0;
Member.Z0(5) = 4;
Member.Xt(1) = 0;
Member.Yt(1) = 35;
Member.Zt(1) = 0;
Member.D(1) = 6.0;
Member.L(1) = sqrt((Member.Xt(1)-Member.X0(1))^2 + (Member.Yt(1)-Member.Y0(1))^2 + (Member.Zt(1)-Member.Z0(1))^2);
Member.fai_y(1) = atand(sqrt((Member.Xt(1)-Member.X0(1))^2 + (Member.Zt(1)-Member.Z0(1))^2) / (Member.Yt(1)-Member.Y0(1)));
if Member.Xt(1) - Member.X0(1) == 0
    Member.cita_x(1) = 90;
else
    Member.cita_x(1) = atand((Member.Zt(1)-Member.Z0(1)) / (Member.Xt(1)-Member.X0(1)));
end
Member.cx(1) = sind(Member.fai_y(1)) * cosd(Member.cita_x(1));
Member.cy(1) = cosd(Member.fai_y(1));
Member.cz(1) = sind(Member.fai_y(1)) * sind(Member.cita_x(1));
Discrete = struct();
Discrete.Num_ele(1) = ceil(Member.L(1));
Discrete.dL(1) = Member.L(1) / Discrete.Num_ele(1);

fclose(fopen(logFile, 'w'));
diary(logFile);
diary on;
fprintf('Step 5 directional performance profile: %s\n', datestr(now));

cfg = build_design_config(struct('load_direction_mode', 1));
scenarios = direction_scenarios(cfg);
nPaper = count_paper_direction_scenarios(scenarios);
fprintf('Direction scenarios (paper): %d\n', nPaper);

floorCtx = struct( ...
    'floor_id', 1, ...
    'Num_bar_array', [1], ...
    'Y0_position', Member.Y0(1), ...
    'Width_i', 10, ...
    'Wnet', 1e6, ...
    'legGeom', struct('leg_ids', [1 2 3 4], 'x', [1 1 -1 -1], 'z', [1 -1 -1 1], 'center_x', 0, 'center_z', 0), ...
    'sitah', 0.5, ...
    'brace_ids', 5, ...
    'F_allowable_leg', 1e7, ...
    'F_allowable_brace', 1e7, ...
    'D_leg', 1.0, ...
    't_leg', 0.04, ...
    'D_brace', 0.6, ...
    't_brace', 0.02, ...
    'L_leg', 20, ...
    'L_brace', 15, ...
    't0', 0, ...
    't1', 2, ...
    'dt', 0.5, ...
    'F_etm', 1e5, ...
    'M_etm', 1e6, ...
    'F_eog', 1e5, ...
    'M_eog', 1e6, ...
    'F_ewm_50', 1e5, ...
    'M_ewm_50', 1e6, ...
    'F_ewm_1', 1e5, ...
    'M_ewm_1', 1e6, ...
    'Hm2', 1, ...
    'Tm2', 10, ...
    'DAF2', 1, ...
    'Hm50', 2, ...
    'Tm50', 12, ...
    'DAF50', 1, ...
    'Hm1', 0.8, ...
    'Tm1', 9, ...
    'DAF1', 1, ...
    'steel_density', 7850, ...
    'hydro_density', 1025, ...
    'deck_weight', 5e6);

tStart = tic;
env = uls_floor_envelope(floorCtx, scenarios, [], cfg);
elapsedEnvelope = toc(tStart);

fprintf('\n--- uls_floor_envelope (one floor, smoke hydro window t1=%g s) ---\n', floorCtx.t1);
fprintf('Elapsed (s): %.3f\n', elapsedEnvelope);
fprintf('Governing: %s / %s\n', env.direction_case, env.environment_case);
fprintf('Cache stats: hits=%d misses=%d evaluations=%d\n', ...
    env.cache_stats.hits, env.cache_stats.misses, env.cache_stats.evaluations);
if env.cache_stats.evaluations > 0
    hitRate = env.cache_stats.hits / env.cache_stats.evaluations;
    fprintf('Cache hit rate: %.3f\n', hitRate);
end
fprintf('Expected combinations: %d directions x 4 env cases = %d\n', nPaper, nPaper * 4);

LegidPfloor = [1, 2, 3, 4];
BraceidPfloor = [5, 6, 7, 8];
tStart = tic;
try
    run_step5_directional_floor(floorCtx, scenarios, cfg, LegidPfloor, BraceidPfloor, 1);
    elapsedFloor = toc(tStart);
    fprintf('\n--- run_step5_directional_floor (floor 1, includes resize loop) ---\n');
    fprintf('Elapsed (s): %.3f\n', elapsedFloor);
catch ME
    elapsedFloor = toc(tStart);
    fprintf('\n--- run_step5_directional_floor skipped after envelope benchmark ---\n');
    fprintf('Partial elapsed (s): %.3f\n', elapsedFloor);
    fprintf('Reason: %s\n', ME.message);
end

fprintf('\nProfile complete. Log: %s\n', logFile);
diary off;
