% Step 10 write_directional_summary tests.
thisFileDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(thisFileDir));
addpath(fullfile(projectRoot, 'modules'));

tempDir = tempname;
mkdir(tempDir);
summaryPath = fullfile(tempDir, 'directional_summary.txt');

summaryPaper = struct( ...
    'mode', 'auto_envelope', ...
    'legacy', [], ...
    'uls', struct( ...
        'direction_case', 'D4', ...
        'beta_wind', 45, ...
        'beta_wave', 45, ...
        'environment_case', 'EWM_50+Hm50', ...
        'floor', 3, ...
        'member_type', 'brace', ...
        'member_id', 12, ...
        'demand', 1.5e6, ...
        'capacity', 1.2e6), ...
    'deflection', struct( ...
        'direction_case', 'D2', ...
        'beta_wind', 0, ...
        'beta_wave', 90, ...
        'environment_case', '1yr_NTM', ...
        'max_deflection', 0.35, ...
        'member_type', 'deflection'));

write_directional_summary(summaryPath, summaryPaper);
text = fileread(summaryPath);
assert(contains(text, '=== Directional Load Summary ==='), 'Missing ULS header');
assert(contains(text, '=== Directional Deflection Summary ==='), 'Missing deflection header');
assert(contains(text, 'governing_direction_case = D4'), 'Missing ULS governing case');
assert(contains(text, 'governing_member_type = brace'), 'Missing ULS member type');
assert(contains(text, 'max_deflection = 0.35 m'), 'Missing deflection value');
fprintf('PASS: write_directional_summary paper dual-section format\n');

summaryLegacy = struct( ...
    'mode', 'legacy_pesai', ...
    'uls', [], ...
    'deflection', [], ...
    'legacy', struct( ...
        'pesai_legacy', 45, ...
        'calculation', 'old scalar formulation', ...
        'purpose', 'regression comparison only'));
legacyPath = fullfile(tempDir, 'directional_summary_legacy.txt');
write_directional_summary(legacyPath, summaryLegacy);
legacyText = fileread(legacyPath);
assert(contains(legacyText, '=== Directional Load Summary (Legacy) ==='), ...
    'Missing legacy header');
assert(contains(legacyText, 'pesai_legacy = 45 deg'), 'Missing legacy angle');
assert(contains(legacyText, 'calculation = old scalar formulation'), ...
    'Missing legacy calculation label');
fprintf('PASS: write_directional_summary legacy format\n');

badSummary = struct('mode', 'auto_envelope', 'legacy', [], 'uls', [], 'deflection', []);
try
    write_directional_summary(fullfile(tempDir, 'bad.txt'), badSummary);
    error('Expected error for missing summary.uls in paper mode.');
catch ME
    assert(strcmp(ME.identifier, 'write_directional_summary:MissingField'), ...
        'Unexpected error: %s', ME.message);
end
fprintf('PASS: write_directional_summary validates required fields\n');

rmdir(tempDir, 's');
fprintf('All write_directional_summary tests passed.\n');
