% Step 9 directional deflection envelope tests.
% Run from repo root (R2018a): matlab -nosplash -nodesktop -r "cd('<repo>'); run('Validations/model/Test_directional_deflection_envelope.m'); exit;"
thisFileDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(thisFileDir));
addpath(fullfile(projectRoot, 'modules'));

cfgAuto = build_design_config(struct('load_direction_mode', 1));
cfgLegacy = build_design_config(struct('load_direction_mode', 2));
scAuto = direction_scenarios(cfgAuto);
scLegacy = direction_scenarios(cfgLegacy);

%% select_governing_deflection picks maximum deflection
caseResults(1) = struct( ...
    'delt_towertop', 0.12, ...
    'direction_case', 'D1', ...
    'beta_wind', 0, ...
    'beta_wave', 0, ...
    'environment_case', '1yr_NTM');
caseResults(2) = struct( ...
    'delt_towertop', 0.18, ...
    'direction_case', 'D2', ...
    'beta_wind', 0, ...
    'beta_wave', 90, ...
    'environment_case', '1yr_NTM');
caseResults(3) = struct( ...
    'delt_towertop', 0.15, ...
    'direction_case', 'D3', ...
    'beta_wind', 0, ...
    'beta_wave', 45, ...
    'environment_case', '1yr_NTM');
envelope = select_governing_deflection(caseResults);
assert(abs(envelope.max_deflection - 0.18) < 1e-12, 'Expected D2 to govern');
assert(strcmp(envelope.direction_case, 'D2'), 'Expected governing case D2');
assert(envelope.beta_wave == 90, 'Expected beta_wave=90 for D2');
assert(envelope.num_cases_evaluated == 3, 'Expected 3 evaluated cases');
fprintf('PASS: select_governing_deflection picks maximum deflection\n');

try
    select_governing_deflection(struct([]));
    error('Expected error for empty caseResults.');
catch ME
    assert(strcmp(ME.identifier, 'select_governing_deflection:EmptyCaseResults'), ...
        'Unexpected error: %s', ME.message);
end
fprintf('PASS: select_governing_deflection rejects empty input\n');

%% Legacy-only scenarios rejected from envelope
minimalDeflectionCtx = struct( ...
    't0', 0, ...
    't1', 0.1, ...
    'dt', 0.1, ...
    'Num_bar_array', 1, ...
    'Y0_position', 0, ...
    'Hm1', 1.0, ...
    'Tm1', 10.0, ...
    'h_total', 100, ...
    'K_R', 1e9, ...
    'EI_Jacket', 1e10, ...
    'EI_JacketTower', 1e10, ...
    'F_ntm', 1e5, ...
    'environment_case', '1yr_NTM');
try
    directional_deflection_envelope(minimalDeflectionCtx, scLegacy, cfgAuto);
    error('Expected error when calling directional_deflection_envelope with legacy-only scenarios.');
catch ME
    assert(strcmp(ME.identifier, 'directional_deflection_envelope:NoPaperScenarios'), ...
        'Unexpected error: %s', ME.message);
end
fprintf('PASS: legacy scenarios excluded from directional_deflection_envelope\n');

%% Envelope output fields for paper scenarios (with hydro fixture)
setupMinimalHydroFixture();
deflectionCtx = struct( ...
    't0', 0, ...
    't1', 2, ...
    'dt', 0.5, ...
    'Num_bar_array', 1, ...
    'Y0_position', 0, ...
    'Hm1', 2.0, ...
    'Tm1', 12.0, ...
    'h_total', 100, ...
    'K_R', 1e9, ...
    'EI_Jacket', 1e10, ...
    'EI_JacketTower', 1e10, ...
    'F_ntm', 1e5, ...
    'environment_case', '1yr_NTM');
scSingle = direction_scenarios(build_design_config(struct('load_direction_mode', 0, 'beta_wind', 0, 'beta_wave', 0)));
envelopeSingle = directional_deflection_envelope(deflectionCtx, scSingle, cfgAuto);
requiredFields = {'max_deflection', 'direction_case', 'beta_wind', 'beta_wave', ...
    'environment_case', 'num_cases_evaluated', 'mode_name', 'scenarios_evaluated'};
for i = 1:numel(requiredFields)
    assert(isfield(envelopeSingle, requiredFields{i}), ...
        'Missing envelope field: %s', requiredFields{i});
end
assert(isfinite(envelopeSingle.max_deflection) && envelopeSingle.max_deflection >= 0, ...
    'max_deflection must be finite and non-negative');
assert(strcmp(envelopeSingle.direction_case, 'SINGLE'), 'Expected SINGLE governing case');
assert(envelopeSingle.scenarios_evaluated == 1, 'Expected one scenario evaluated');
fprintf('PASS: directional_deflection_envelope output fields and single scenario\n');

%% auto_envelope D1-D4 integration (4 paper scenarios)
deflectionCtx.use_directional_hydro = true;
envelopeAuto = directional_deflection_envelope(deflectionCtx, scAuto, cfgAuto);
assert(envelopeAuto.scenarios_evaluated == 4, ...
    'auto_envelope must evaluate 4 paper scenarios');
assert(envelopeAuto.num_cases_evaluated == 4, ...
    'auto_envelope must record 4 evaluated cases');
assert(isfinite(envelopeAuto.max_deflection) && envelopeAuto.max_deflection >= 0, ...
    'auto_envelope max_deflection must be finite and non-negative');
assert(any(strcmp(envelopeAuto.direction_case, {'D1', 'D2', 'D3', 'D4'})), ...
    'governing direction_case must be one of D1-D4');
matchedScenario = scAuto(strcmp({scAuto.id}, envelopeAuto.direction_case));
assert(~isempty(matchedScenario), 'governing case must match an auto scenario id');
assert(envelopeAuto.beta_wind == matchedScenario.beta_wind, ...
    'governing beta_wind must match scenario metadata');
assert(envelopeAuto.beta_wave == matchedScenario.beta_wave, ...
    'governing beta_wave must match scenario metadata');
assert(strcmp(envelopeAuto.environment_case, '1yr_NTM'), ...
    'auto_envelope environment_case must be 1yr_NTM');
perCaseDeflection = zeros(1, numel(scAuto));
for i = 1:numel(scAuto)
    caseOut = compute_towertop_deflection_case(deflectionCtx, ...
        scAuto(i).beta_wind, scAuto(i).beta_wave);
    perCaseDeflection(i) = caseOut.delt_towertop;
end
assert(abs(envelopeAuto.max_deflection - max(perCaseDeflection)) < 1e-9, ...
    'auto_envelope max_deflection must equal per-case maximum');
fprintf('PASS: directional_deflection_envelope auto_envelope D1-D4 integration\n');

%% Legacy vs directional hydro flag on compute_towertop_deflection_case
deflectionCtxLegacy = deflectionCtx;
deflectionCtxLegacy.use_directional_hydro = false;
deflectionCtxDirectional = deflectionCtx;
deflectionCtxDirectional.use_directional_hydro = true;
legacyCase = compute_towertop_deflection_case(deflectionCtxLegacy, 0, 0);
directionalCase = compute_towertop_deflection_case(deflectionCtxDirectional, 0, 0);
assert(abs(legacyCase.F1_wav - directionalCase.F1_wav) < 1e-6 * max(1, abs(legacyCase.F1_wav)), ...
    'beta_wave=0 directional hydro should match legacy hydro force');
assert(abs(legacyCase.delt_towertop - directionalCase.delt_towertop) < 1e-9, ...
    'beta_wave=0 deflection should match legacy path');
fprintf('PASS: compute_towertop_deflection_case legacy/directional beta=0 parity\n');

fprintf('All Step 9 directional deflection envelope tests passed.\n');

function setupMinimalHydroFixture()
global Member Hydro Wave Current Discrete debug dL_ele_target;

debug = 0;
dL_ele_target = 3.0;
Hydro = struct('density', 1025, 'cd', 1.0, 'cm', 2.0);
Wave = struct('S', 50, 'T', 12, 'h', 2, 'k', 0.05, 'beta_propagation', 0);
Current = struct('U_ss0', 0, 'U_ns0', 0, 'h_ref', 20);

Member.X0(1) = 6;
Member.Y0(1) = 0;
Member.Z0(1) = 6;
Member.Xt(1) = 4;
Member.Yt(1) = 20;
Member.Zt(1) = 4;
Member.D(1) = 1.0;
Member.t(1) = 0.05;
Member.L(1) = sqrt(sum(([Member.Xt(1), Member.Yt(1), Member.Zt(1)] - [Member.X0(1), Member.Y0(1), Member.Z0(1)]).^2));
Member.fai_y(1) = atand(sqrt((Member.Xt(1)-Member.X0(1))^2 + (Member.Zt(1)-Member.Z0(1))^2) / abs(Member.Yt(1)-Member.Y0(1)));
Member.cita_x(1) = atand((Member.Zt(1)-Member.Z0(1)) / (Member.Xt(1)-Member.X0(1)));
[Member.cx(1), Member.cy(1), Member.cz(1)] = Direction_bar(Member.fai_y(1), Member.cita_x(1));
Discrete.Num_ele(1) = 4;
Discrete.dL(1) = Member.L(1) / Discrete.Num_ele(1);
end
